version: "3.8"
services:
  client:
    build:
      context: ./FrontEnd
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./BackEnd
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: kyc_db
      JWT_SECRET: hihi
      PORT: 8080

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kyc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
# docker-compose up --build --detach
